In [ ]:
source activate cs231n
source deactivate cs231n

In [1]:
import numpy as np

In [ ]:
y = np.random.rand(10,1)
X = np.random.rand(10,2)
X.shape, y.shape
X1 = np.random.rand(10,2)

In [72]:
class Knearest_classifier:
    #def __init__(self):
        #pass
    
    def train(self, X, y):
        self.X = X
        self.y = y
        
    def test(self, X):
        
        num = X.shape[0]
        
        Pred = np.zeros(num, dtype=self.y.dtype)
        
        for i in range(num):
            
            distance = np.sum(np.abs(self.X - X[i,:]), axis=1)
            
            min_distance = np.argmin(distance)
            
            Pred[i] = self.y[min_distance]
            
        return Pred

In [73]:
d = Knearest_classifier()
d.train(X,y)

In [75]:
d.test(X)

array([0.76919799, 0.54082469, 0.26826426, 0.73303072, 0.00733151,
       0.89609054, 0.20920713, 0.8413235 , 0.48788662, 0.88460406])

In [ ]:
# Loss function and 

## lecture 6 Trainning CNN

In [2]:
import numpy as np

In [4]:
count = 10
for i in range(count):
    rt = 10**np.random.uniform(-5,5,10) # unifrom distribution 
print(rt)

[2.02770041e+03 2.13184958e+00 6.53611063e+04 1.82194433e-05
 2.79366120e-05 4.77287245e+01 3.18520021e+03 7.31658661e-02
 5.80733079e+02 1.46389348e+04]


In [ ]:
### SVM loss function in two form unvectorized and vectorised 

In [5]:
def L_i(x, y, W):
  """
  unvectorized version. Compute the multiclass svm loss for a single example (x,y)
  - x is a column vector representing an image (e.g. 3073 x 1 in CIFAR-10)
    with an appended bias dimension in the 3073-rd position (i.e. bias trick)
  - y is an integer giving index of correct class (e.g. between 0 and 9 in CIFAR-10)
  - W is the weight matrix (e.g. 10 x 3073 in CIFAR-10)
  """
    delta = 1.0 # see notes about delta later in this section
    scores = W.dot(x) # scores becomes of size 10 x 1, the scores for each class
    correct_class_score = scores[y]
    D = W.shape[0] # number of classes, e.g. 10
    loss_i = 0.0
    for j in xrange(D): # iterate over all wrong classes
        if j == y:
      # skip for the true class to only loop over incorrect classes
          continue
    # accumulate loss for the i-th example
        loss_i += max(0, scores[j] - correct_class_score + delta)
    return loss_i

def L_i_vectorized(x, y, W):
    """
    A faster half-vectorized implementation. half-vectorized
    refers to the fact that for a single example the implementation contains
    no for loops, but there is still one loop over the examples (outside this function)
    """
    delta = 1.0
    scores = W.dot(x)
    # compute the margins for all classes in one vector operation
    margins = np.maximum(0, scores - scores[y] + delta)
    # on y-th position scores[y] - scores[y] canceled and gave delta. We want
    # to ignore the y-th position and only consider margin on max wrong class
    margins[y] = 0
    loss_i = np.sum(margins)
    return loss_i

def L(X, y, W):
  """
  fully-vectorized implementation :
  - X holds all the training examples as columns (e.g. 3073 x 50,000 in CIFAR-10)
  - y is array of integers specifying correct class (e.g. 50,000-D array)
  - W are weights (e.g. 10 x 3073)
  """
  # evaluate loss over all examples in X without using any for loops
  # left as exercise to reader in the assignment

# Soft max loss function for multi class `

In [ ]:
f = np.array([123, 456, 789]) # example with 3 classes and each having large scores
p = np.exp(f) / np.sum(np.exp(f)) # Bad: Numeric problem, potential blowup

# instead: first shift the values of f so that the highest number is 0:
f -= np.max(f) # f becomes [-666, -333, 0]
p = np.exp(f) / np.sum(np.exp(f)) # safe to do, gives the correct answer


# Test KNN

In [59]:
train = np.arange(9).reshape(3,3)*2

In [69]:
test = np.arange(3).reshape(1,3)*1

In [70]:
train.shape, test.shape

((3, 3), (1, 3))

In [76]:
def calc_dist_euc(test, train):
    shape_test = test.shape[0]
    shape_train = train.shape[0]
    distance = np.zeros((shape_test, shape_train))
    for u in range(shape_test):
        for j in range(shape_train):
            distance[u,j] = np.sum(test[u] - train[j])**2
    return distance
calc_dist_euc(test, train)

array([[   9.,  441., 1521.]])

* end test KNN * 

* Use argsort NP *

In [78]:
import numpy as np

In [82]:
data = np.array([[1,2,3,4,5] , [0,2,58,5,5]])
np.argsort(data)

array([[0, 1, 2, 3, 4],
       [0, 1, 3, 4, 2]])

***Practical issues: Numeric stability***

When you’re writing code for computing the Softmax function in practice, 
the intermediate terms efyi and ∑jefj may be very large due to the exponentials. 
Dividing large numbers can be numerically unstable, so it is important to use a normalization trick. 
Notice that if we multiply the top and bottom of the fraction by a constant C and push it into the sum, we get 
the following (mathematically equivalent) expression:

In [ ]:
f = np.array([123, 456, 789]) # example with 3 classes and each having large scores
p = np.exp(f) / np.sum(np.exp(f)) # Bad: Numeric problem, potential blowup

# instead: first shift the values of f so that the highest number is 0:
f -= np.max(f) # f becomes [-666, -333, 0]
p = np.exp(f) / np.sum(np.exp(f)) # safe to do, gives the correct answer